// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GMMessage.proto

#include "GMMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class ReqGMCloseServerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReqGMCloseServer>
      _instance;
} _ReqGMCloseServer_default_instance_;
class ResGMCloseServerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResGMCloseServer>
      _instance;
} _ResGMCloseServer_default_instance_;
namespace protobuf_GMMessage_2eproto {
void InitDefaultsReqGMCloseServerImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_ReqGMCloseServer_default_instance_;
    new (ptr) ::ReqGMCloseServer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ReqGMCloseServer::InitAsDefaultInstance();
}

void InitDefaultsReqGMCloseServer() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsReqGMCloseServerImpl);
}

void InitDefaultsResGMCloseServerImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_ResGMCloseServer_default_instance_;
    new (ptr) ::ResGMCloseServer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ResGMCloseServer::InitAsDefaultInstance();
}

void InitDefaultsResGMCloseServer() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsResGMCloseServerImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ReqGMCloseServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ReqGMCloseServer, msgid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ReqGMCloseServer, resmsg_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ResGMCloseServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ResGMCloseServer, msgid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ResGMCloseServer, resmsg_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ReqGMCloseServer)},
  { 7, -1, sizeof(::ResGMCloseServer)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ReqGMCloseServer_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ResGMCloseServer_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "GMMessage.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017GMMessage.proto\032\017MessageId.proto\"9\n\020Re"
      "qGMCloseServer\022\025\n\005msgId\030\001 \001(\0162\006.MsgId\022\016\n"
      "\006resMsg\030\002 \001(\t\"9\n\020ResGMCloseServer\022\025\n\005msg"
      "Id\030\001 \001(\0162\006.MsgId\022\016\n\006resMsg\030\002 \001(\tB)\n%info"
      ".xiaomo.server.shared.protocol.gmP\001b\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 203);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GMMessage.proto", &protobuf_RegisterTypes);
  ::protobuf_MessageId_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_GMMessage_2eproto

// ===================================================================

void ReqGMCloseServer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqGMCloseServer::kMsgIdFieldNumber;
const int ReqGMCloseServer::kResMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqGMCloseServer::ReqGMCloseServer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_GMMessage_2eproto::InitDefaultsReqGMCloseServer();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ReqGMCloseServer)
}
ReqGMCloseServer::ReqGMCloseServer(const ReqGMCloseServer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  resmsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.resmsg().size() > 0) {
    resmsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.resmsg_);
  }
  msgid_ = from.msgid_;
  // @@protoc_insertion_point(copy_constructor:ReqGMCloseServer)
}

void ReqGMCloseServer::SharedCtor() {
  resmsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_ = 0;
  _cached_size_ = 0;
}

ReqGMCloseServer::~ReqGMCloseServer() {
  // @@protoc_insertion_point(destructor:ReqGMCloseServer)
  SharedDtor();
}

void ReqGMCloseServer::SharedDtor() {
  resmsg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReqGMCloseServer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReqGMCloseServer::descriptor() {
  ::protobuf_GMMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GMMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReqGMCloseServer& ReqGMCloseServer::default_instance() {
  ::protobuf_GMMessage_2eproto::InitDefaultsReqGMCloseServer();
  return *internal_default_instance();
}

ReqGMCloseServer* ReqGMCloseServer::New(::google::protobuf::Arena* arena) const {
  ReqGMCloseServer* n = new ReqGMCloseServer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReqGMCloseServer::Clear() {
// @@protoc_insertion_point(message_clear_start:ReqGMCloseServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  resmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_ = 0;
  _internal_metadata_.Clear();
}

bool ReqGMCloseServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ReqGMCloseServer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .MsgId msgId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_msgid(static_cast< ::MsgId >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string resMsg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_resmsg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->resmsg().data(), static_cast<int>(this->resmsg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ReqGMCloseServer.resMsg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ReqGMCloseServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ReqGMCloseServer)
  return false;
#undef DO_
}

void ReqGMCloseServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ReqGMCloseServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MsgId msgId = 1;
  if (this->msgid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgid(), output);
  }

  // string resMsg = 2;
  if (this->resmsg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->resmsg().data(), static_cast<int>(this->resmsg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ReqGMCloseServer.resMsg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->resmsg(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ReqGMCloseServer)
}

::google::protobuf::uint8* ReqGMCloseServer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ReqGMCloseServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MsgId msgId = 1;
  if (this->msgid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgid(), target);
  }

  // string resMsg = 2;
  if (this->resmsg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->resmsg().data(), static_cast<int>(this->resmsg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ReqGMCloseServer.resMsg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->resmsg(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ReqGMCloseServer)
  return target;
}

size_t ReqGMCloseServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ReqGMCloseServer)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string resMsg = 2;
  if (this->resmsg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->resmsg());
  }

  // .MsgId msgId = 1;
  if (this->msgid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReqGMCloseServer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ReqGMCloseServer)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqGMCloseServer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqGMCloseServer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ReqGMCloseServer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ReqGMCloseServer)
    MergeFrom(*source);
  }
}

void ReqGMCloseServer::MergeFrom(const ReqGMCloseServer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ReqGMCloseServer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.resmsg().size() > 0) {

    resmsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.resmsg_);
  }
  if (from.msgid() != 0) {
    set_msgid(from.msgid());
  }
}

void ReqGMCloseServer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ReqGMCloseServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqGMCloseServer::CopyFrom(const ReqGMCloseServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReqGMCloseServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqGMCloseServer::IsInitialized() const {
  return true;
}

void ReqGMCloseServer::Swap(ReqGMCloseServer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqGMCloseServer::InternalSwap(ReqGMCloseServer* other) {
  using std::swap;
  resmsg_.Swap(&other->resmsg_);
  swap(msgid_, other->msgid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReqGMCloseServer::GetMetadata() const {
  protobuf_GMMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GMMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ResGMCloseServer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResGMCloseServer::kMsgIdFieldNumber;
const int ResGMCloseServer::kResMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResGMCloseServer::ResGMCloseServer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_GMMessage_2eproto::InitDefaultsResGMCloseServer();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ResGMCloseServer)
}
ResGMCloseServer::ResGMCloseServer(const ResGMCloseServer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  resmsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.resmsg().size() > 0) {
    resmsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.resmsg_);
  }
  msgid_ = from.msgid_;
  // @@protoc_insertion_point(copy_constructor:ResGMCloseServer)
}

void ResGMCloseServer::SharedCtor() {
  resmsg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_ = 0;
  _cached_size_ = 0;
}

ResGMCloseServer::~ResGMCloseServer() {
  // @@protoc_insertion_point(destructor:ResGMCloseServer)
  SharedDtor();
}

void ResGMCloseServer::SharedDtor() {
  resmsg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ResGMCloseServer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ResGMCloseServer::descriptor() {
  ::protobuf_GMMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GMMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResGMCloseServer& ResGMCloseServer::default_instance() {
  ::protobuf_GMMessage_2eproto::InitDefaultsResGMCloseServer();
  return *internal_default_instance();
}

ResGMCloseServer* ResGMCloseServer::New(::google::protobuf::Arena* arena) const {
  ResGMCloseServer* n = new ResGMCloseServer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ResGMCloseServer::Clear() {
// @@protoc_insertion_point(message_clear_start:ResGMCloseServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  resmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_ = 0;
  _internal_metadata_.Clear();
}

bool ResGMCloseServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ResGMCloseServer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .MsgId msgId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_msgid(static_cast< ::MsgId >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string resMsg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_resmsg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->resmsg().data(), static_cast<int>(this->resmsg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ResGMCloseServer.resMsg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ResGMCloseServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ResGMCloseServer)
  return false;
#undef DO_
}

void ResGMCloseServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ResGMCloseServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MsgId msgId = 1;
  if (this->msgid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->msgid(), output);
  }

  // string resMsg = 2;
  if (this->resmsg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->resmsg().data(), static_cast<int>(this->resmsg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ResGMCloseServer.resMsg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->resmsg(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ResGMCloseServer)
}

::google::protobuf::uint8* ResGMCloseServer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ResGMCloseServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MsgId msgId = 1;
  if (this->msgid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->msgid(), target);
  }

  // string resMsg = 2;
  if (this->resmsg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->resmsg().data(), static_cast<int>(this->resmsg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ResGMCloseServer.resMsg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->resmsg(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ResGMCloseServer)
  return target;
}

size_t ResGMCloseServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ResGMCloseServer)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string resMsg = 2;
  if (this->resmsg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->resmsg());
  }

  // .MsgId msgId = 1;
  if (this->msgid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->msgid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ResGMCloseServer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ResGMCloseServer)
  GOOGLE_DCHECK_NE(&from, this);
  const ResGMCloseServer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResGMCloseServer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ResGMCloseServer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ResGMCloseServer)
    MergeFrom(*source);
  }
}

void ResGMCloseServer::MergeFrom(const ResGMCloseServer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ResGMCloseServer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.resmsg().size() > 0) {

    resmsg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.resmsg_);
  }
  if (from.msgid() != 0) {
    set_msgid(from.msgid());
  }
}

void ResGMCloseServer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ResGMCloseServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResGMCloseServer::CopyFrom(const ResGMCloseServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResGMCloseServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResGMCloseServer::IsInitialized() const {
  return true;
}

void ResGMCloseServer::Swap(ResGMCloseServer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResGMCloseServer::InternalSwap(ResGMCloseServer* other) {
  using std::swap;
  resmsg_.Swap(&other->resmsg_);
  swap(msgid_, other->msgid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ResGMCloseServer::GetMetadata() const {
  protobuf_GMMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_GMMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
